# Generated by Django 5.1.2 on 2024-10-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
