# Generated by Django 5.1.2 on 2024-11-21 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=250, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('pais', models.CharField(max_length=100, null=True)),
                ('ciudad', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True, null=True)),
                ('contactoPrincipa', models.CharField(max_length=100, null=True)),
                ('nombreContacto', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='Estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fechaIngreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fechaVencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='stockMinimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ubicacion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ultimaSalida',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='limiteGarantia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidadMedida',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='modeloCompatible',
            field=models.ManyToManyField(to='inventario.modelo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='Proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor'),
        ),
    ]
