# Generated by Django 5.1.2 on 2024-11-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_modelo_proveedor_remove_inventario_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='limiteGarantia',
        ),
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
