# Generated by Django 5.1.2 on 2024-11-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_inventario_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fechaIngreso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
