# Generated by Django 5.1.2 on 2024-11-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventario_fechaingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Proveedor',
            new_name='proveedor',
        ),
    ]
