# Generated by Django 4.2.7 on 2024-12-13 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('nota', models.TextField(blank=True, null=True)),
                ('plazo', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('tipo_trabajo', models.CharField(max_length=100)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('planificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('mensaje', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reporte.tarea')),
            ],
        ),
    ]
