# Generated by Django 4.2.7 on 2024-12-15 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='creador',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_finalizacion',
            new_name='fechaFinalizacion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='operario',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='planificador',
        ),
        migrations.AddField(
            model_name='tarea',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='plazo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
