# Generated by Django 5.1.2 on 2024-11-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='anio',
        ),
    ]
