# Generated by Django 5.1.2 on 2024-11-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_remove_modelo_anio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Kilometraje',
            new_name='kilometraje',
        ),
    ]
