# Generated by Django 5.1.2 on 2024-12-15 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_rename_kilometraje_vehiculo_kilometraje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, null=True)),
                ('rut', models.CharField(max_length=20, null=True, unique=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_contacto', models.CharField(max_length=255, null=True)),
                ('cargo_contacto', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=50, null=True)),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
            ],
        ),
    ]
