# Generated by Django 5.1.2 on 2024-12-15 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0006_producto_precio'),
        ('vehiculo', '0003_rename_kilometraje_vehiculo_kilometraje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(null=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('revision_inicial', models.CharField(blank=True, max_length=650, null=True)),
                ('precio_total', models.IntegerField(null=True)),
                ('otroServicio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Cotizacion', 'Cotización'), ('Cotizacion Autorizada', 'Cotización Autorizada'), ('Completada', 'Completada'), ('En Proceso', 'En Proceso'), ('Descartada', 'Descartada'), ('Revision', 'Revisión')], default='Cotizacion', max_length=50)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantencion.mantencion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='mantencion',
            name='productosUtilizado',
            field=models.ManyToManyField(blank=True, through='mantencion.ProductoUtilizado', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='servicio',
            field=models.ManyToManyField(blank=True, to='mantencion.servicio'),
        ),
    ]
