# Generated by Django 5.1.2 on 2024-12-15 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_precio'),
        ('mantencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEnMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantencion.mantencion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='productosUtilizado',
            field=models.ManyToManyField(blank=True, through='mantencion.ProductoEnMantencion', to='inventario.producto'),
        ),
    ]
