# Generated by Django 5.1.2 on 2024-12-15 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0002_productoenmantencion_and_more'),
        ('vehiculo', '0003_rename_kilometraje_vehiculo_kilometraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantencion',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo'),
        ),
    ]
