# Generated by Django 5.1.2 on 2024-12-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0003_alter_mantencion_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoenmantencion',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
