# Generated by Django 5.1.2 on 2024-12-16 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0004_alter_productoenmantencion_precio_total'),
        ('reporte', '0003_tarea_asignado_a'),
        ('vehiculo', '0004_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.cliente'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='recepcionista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='reporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporte.reporte'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporte.tarea'),
        ),
    ]
